name: Generate 3D Contributions

on:
  schedule:
    # setiap hari pukul 12:48 WIB → 05:48 UTC
    - cron: '12 6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Ensure assets folder exists
        run: mkdir -p assets

      - name: Generate 3D contributions image
        uses: liilr/github-profile-3d-contrib@main
        with:
          username: ${{ github.actor }}
          output: assets/3d-contrib.png
          theme: night-green
          cube-size: 12
          cube-gap: 2
          rotate-x: 60
          rotate-y: 30
          width: 1024
          height: 256
          format: png
          # Jika Action mendukung cache-seconds:
          # cache-seconds: 3600

      - name: Commit generated image
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/3d-contrib.png
          git commit -m "chore: update 3D contributions image" || echo "No changes to commit"
          git push
