name: Generate 3D Contributions

on:
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Ensure output directory exists
        run: mkdir -p profile-3d-contrib

      - name: Generate 3D contributions (SVG, night-green)
        uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME:     ${{ github.repository_owner }}
          THEME:        night-green
          CUBE_SIZE:    12
          CUBE_GAP:     2
          ROTATE_X:     60
          ROTATE_Y:     30
          WIDTH:        1024
          HEIGHT:       256
          FORMAT:       svg

      - name: List generated file
        run: |
          echo "=== profile-3d-contrib/ ==="
          ls -1 profile-3d-contrib

      - name: Commit & Push SVG
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # Ambil semua SVG di profile-3d-contrib dan commit
          git add profile-3d-contrib/*.svg
          git commit -m "chore: update 3D contributions SVG (night-green)" || echo "No changes to commit"
          git push