name: Generate 3D Contributions

on:
  schedule:
    - cron: '30 6 * * *'
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: mkdir -p assets
        name: Ensure assets folder exists

      - name: Generate 3D contributions image
        uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME:     ${{ github.repository_owner }}
          OUTPUT:       assets/3d-contrib.png
          THEME:        night-green
          CUBE_SIZE:    12
          CUBE_GAP:     2
          ROTATE_X:     60
          ROTATE_Y:     30
          WIDTH:        1024
          HEIGHT:       256
          FORMAT:       png

      - name: Debug: list assets folder
        run: |
          echo "=== Listing assets folder ==="
          ls -R assets

      - name: Commit & Push generated image
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/3d-contrib.png
          git commit -m "chore: update 3D contributions image" || echo "No changes to commit"
          git push
