name: Generate 3D Contributions

on:
  schedule:
    # Setiap hari pukul 12:48 WIB → 05:48 UTC
    - cron: '48 5 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Ensure assets folder exists
        run: mkdir -p assets

      - name: Generate 3D contributions image
        uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME:     AqilYogaPramono
          OUTPUT:       assets/
          THEME:        night-green
          CUBE_SIZE:    12
          CUBE_GAP:     2
          ROTATE_X:     60
          ROTATE_Y:     30
          WIDTH:        1024
          HEIGHT:       256
          FORMAT:       png

      - name: Debug list assets folder
        run: |
          echo "=== Listing assets folder ==="
          ls -la assets

      - name: Commit & Push generated image
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/3d-contrib.png
          git commit -m "chore: update 3D contributions image" || echo "No changes to commit"
          git push
